#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
int main()
{
    cin.tie(0);cin.sync_with_stdio(0);
    cout.tie(0);cout.sync_with_stdio(0);
    int t = 1;
    cin >> t;
    while (t--)
    {
        int num;
        cin>>num;
        int count=0;
        int s1=0, s2=0;
        while(num>0)
        {
            if(count<=3)
            {
                
            }
        }
    }
    return 0;
}